run:
  # timeout for analysis
  timeout: 4m

linters-settings:
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true

  tagliatelle:
    case:
      rules:
        json: snake

  whitespace:
    multi-func: true
    multi-if: true

  gosec:
    excludes:
      - G402 # Look for bad TLS connection settings.
      - G306 # Poor file permissions used when writing to a new file.
      - G601 # Implicit memory aliasing in for loop.
      - G115 # Integer overflow in conversion.

  staticcheck:
    checks: ["-SA1019"]

linters:
  enable:
    - gofmt
    - whitespace
    - gosec
